In [1]:
from google.colab import data_table
data_table.enable_dataframe_formatter()

In [2]:
cd "/content/drive/MyDrive/Data Analytics/Datasets"

/content/drive/MyDrive/Data Analytics/Datasets


## Using Confusion Tree on Iris Dataset

Using the iris dataset provided in the sklearn toy datasets library, model a decision tree algorithm that is trained on this dataset. After fitting the algorithm on the training dataset, predict the values using the test dataset.

After that print the confusion matrix for the predicted test dataset.

Note: Use randomstate=42 for traintest_split.

Print the confusion matrix for the predicted test dataset

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

iris = datasets.load_iris()

x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

confusion_matrix = confusion_matrix(y_test, y_pred)

print(confusion_matrix)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


## Classify Kyphosis disease using Decision Trees

Given the "kyphosis.csv" dataset.

- Kyphosis is an abnormally excessive convex curvature of the spine. The kyphosis data frame has 81 rows and 4 columns. representing data on children who have had corrective spinal surgery. The dataset contains 3 inputs and 1 output

Input Columns:

- Age: in months
- Number: the number of vertebrae involved
- Start: the number of the first (topmost) vertebra operated on.
Output Column:

- Kyphosis: a factor with levels absent present indicating if a kyphosis (a type of deformation) was present after the operation.
Link to the dataset:

https://www.kaggle.com/abbasit/kyphosis-dataset

Model a decision tree algorithm that is trained on this dataset. After fitting the algorithm on the training dataset, predict the values using the test dataset.

After that print the confusion matrix for the predicted test dataset.

Note: Use randomstate=42 for traintest_split.

Expected Output

Print the confusion matrix for the predicted test dataset

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("kyphosis.csv")

x = df.iloc[:, 1:]
y = df.iloc[:, 0]

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

print(confusion_matrix(y_test, y_pred))

[[14  1]
 [ 4  2]]


In [5]:
df.head()

Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15