What is Numpy: a
NumPy Basics: b
Creating Different NumPy Arrays: a
What will be the output: d
What will be the output: c

In [2]:
import numpy as np

b = np.empty(2, dtype = int)
b[0] = 1
print(b)

[         1 1065353216]


In [ ]:
import numpy as np
b = [1, 2, 3]
a = np.array(b)
print(a*3, end = "")
a = np.array(b*3)
print(a)

In [ ]:
a = np.empty(4, dtype = int)
print(a)

In [19]:
import numpy as np

np.random.seed(0)
random = np.random.randint(100)
np.random.seed(0)
random2 = np.random.randint(100)
random3 = np.random.randint(100)

print(random)
print(random2)
print(random3)

44
44
47


In [2]:
# importing random module
import random

random.seed(3)

# print a random number between 1 and 1000.
print(random.randint(1, 1000))

# if you want to get the same random number again then,
random.seed(3)
print(random.randint(1, 1000))

# If seed function is not used

# Gives totally unpredictable responses.
print(random.randint(1, 1000))


244
244
607


In [29]:
import numpy as np
import random

array = np.full((3,3), np.random.randint(9))
print(array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [7]:
np.random.randint(10, size = (4,4))

array([[5, 2, 9, 1],
       [6, 0, 0, 0],
       [4, 4, 6, 2],
       [1, 9, 2, 0]])

In [5]:
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(s)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]


In [6]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [10]:
import numpy as np
arr = np.array([10, 20, 30, 15, 18, 36])
new_arr = arr[(arr%5 == 0) & (arr>10)]
print(new_arr)

[20 30 15]


In [11]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [12]:
import numpy as np 
dt = np.dtype('>i4') 
print(dt.name)

int32


### Broadcasting

In [7]:
import numpy as np
import csv

with open("year2017.csv") as file_obj:
    
    file_data = csv.DictReader(file_obj, skipinitialspace = True)
    file_list = list(file_data)
    
    a = np.array(file_list)

{'Year': '2017', 'Month': '1', 'Day': '2', 'Country': 'Afghanistan', 'Region': 'South Asia', 'city': 'Takhta Pul', 'latitude': '31.320556', 'longitude': '65.961111', 'AttackType': 'Hostage Taking (Kidnapping)', 'Killed': '0.0', 'Wounded': '0.0', 'Target': 'Construction Workers', 'Group': 'Taliban', 'Target_type': 'Business', 'Weapon_type': 'Firearms', 'casualities': '0.0'}

### Activity

In [48]:
import numpy as np
import csv

with open("nyc_taxis.csv") as file_obj:
    
    file_data = csv.reader(file_obj, skipinitialspace = True)
    file_list = list(file_data)
    a = np.array(file_list[1:])
    
    distances = np.array(a[:,7], dtype = float)
    times = np.array(a[:,8], dtype = float)
    times /= 3600
    
    speeds = distances/times
    
    print("Mean Speed: ", np.mean(speeds))
    print("May Rides: ", len(a[a[:,1] == '5']))
    tip_50 = np.array(a[:,12], dtype = float)
    tip_50 = tip_50[tip_50>50.0]
    print("Tip > 50: ", len(tip_50))
    print("JFK drop: ", len(a[a[:,6] == '2']))
    
    
    
    

Mean Speed:  32.24258580925573
May Rides:  16650
Tip > 50:  16
JFK drop:  11832


0 pickup_year
1 pickup_month
2 pickup_day
3 pickup_dayofweek
4 pickup_time
5 pickup_location_code
6 dropoff_location_code
7 trip_distance
8 trip_length
9 fare_amount
10 fees_amount
11 tolls_amount
12 tip_amount
13 total_amount
14 payment_type
